# makefile for genome project

f77 = f77
cc = cc
LFLAG = 

FILES = second.o mclock.o

GENOMEc  = main3c.o frag_gen3.o seq_gen.o mat_gen.o rand.o
GENOME2c = set_bit.o get_bit.o get_list.o statd.o
NEXTC = nextc.o

INC1 = libp4_f.a libp4.a
INC2 = libp4_f.a libp4.a p4_fmain.o

mainc:	$(GENOMEc) $(GENOME2c) $(NEXTC) $(FILES)
	f77  -O $(GENOMEc) $(GENOME2c) $(FILES) $(NEXTC) $(INC1) -o mainc
	f77  -O $(NEXTC) $(FILES) $(INC2) -o slave

.f.o : ;	$(f77) -O -c $*.f
.c.o : ;	$(cc)  -O -c $*.c
