# makefile for genome project

FILES = second.o mclock.o
GENOME  = main3b.o frag_gen3.o seq_gen.o mat_gen.o rand.o
GENOME2 = set_bit.o get_bit.o get_list.o statb.o nextb.o

GENOMEc  = main3c.o frag_gen3.o seq_gen.o mat_gen.o rand.o
GENOME2c = set_bit.o get_bit.o get_list.o statd.o nextc.o

GENOMEd  = main3c.o frag_gen3.o seq_gen.o mat_gen.o rand.o
GENOME2d = set_bit.o get_bit.o get_list.o statd.o nextd.o

main:	$(GENOME) $(GENOME2) $(FILES)
	f77  -O $(GENOME) $(GENOME2) $(FILES) -o main

mainc:	$(GENOMEc) $(GENOME2c) $(FILES)
	f77  -O $(GENOMEc) $(GENOME2c) $(FILES) -o mainc

maind:	$(GENOMEd) $(GENOME2d) $(FILES)
	f77  -O $(GENOMEd) $(GENOME2d) $(FILES) -o maind

.f.o : ;	f77 -O -c $*.f
.c.o : ;	cc  -O -c $*.c
